url: http://jgan.xii.cc
title: JGan's
author:
  name: Justin Gan
  email: jgan@xii.cc
description: >-
  JGAN (Justin Gan)
#
theme: minima
minima:
  skin: auto
#
exclude:
  - .gitignore
  - .github
  - .prettierrc
  - README.md
