title: JGan's Home
author:
  name: Justin Gan
  email: jgan@xii.cc
description: >-
  JGAN (Justin Gan)

url: "https://jgan.xii.cc"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

theme: minima
minima:
  skin: auto

exclude:
  - .gitignore
  - .prettierrc
  - README.md
