title: JGan's Home
author:
  name: Justin Gan
  email: jgan@xii.cc

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

remote_theme: jekyll/minima
minima:
  skin: auto

exclude:
  - .gitignore
  - .prettierrc
  - CNAME
  - README.md
